let data = 
[
    ["およそ５００円","about five hundred yen"],
    ["空港に着く","get to the airport"],
    ["（人）に怒っている","be angry with sb"],
    ["野球をする","play baseball"],
    ["お金を持ってくる","bring money"],
    ["ビートルズのCDを聴く","listen to Beatle’s CD"],
    ["５０セント （硬貨）","fifty cents"],
    ["死んでいる","be dead"],
    ["遠くない","be not far"],
    ["フォークを使う","use a fork"],
    ["ドアを引く","pull a door"],
    ["音楽を聞く","listen to music"],
    ["塩を入れる","put salt"],
    ["（物）を～に戻す","return sth to"],
    ["椅子に座る","sit on a chair"],
    ["滑らかな肌","smooth skin"],
    ["ズボンを履いている","wear pants / jeans"],
    ["うるさい","be noisy"],
    ["１０時に","at ten o’clock"],
    ["海で","in the ocean"],
    ["ペンで書く","write with a pen"],
    ["車のお金を払う","pay for a car"],
    ["今日","today"],
    ["トイレにいく","go to the toilet"],
    ["トマトを切る","cut a tomato"],
    ["とても良い","very good"],
    ["を使う","use"],
    ["上に","up"],
    ["着物を着る","wear a kimono"],
    ["良い天気","good weather"],
    ["はい","yes"],
    ["昨日","yesterday"],
    ["交通事故","a traffic accident"],
    ["アクセントがある","have an accent"],
    ["馬に乗る","ride a horse"],
    ["彼女を助ける","help her"],
    ["偉大な、すごい人","a great person"],
    ["育つ","grow"],
    ["水を飲む","drink water"],
    ["車を運転する","drive (a car)"],
    ["簡単な問題","an easy problem"],
    ["彼を見つける","find him"],
    ["太った、太っている男","a fat man"],
    ["ナイフを使う","use a knife"],
    ["台所で","in the kitchen"],
    ["湖で、に","in the lake"],
    ["美しい女性","a beautiful lady"],
    ["教授と話す","talk to a professor"],
    ["地球の周りを","around the planet"],
    ["公園で遊ぶ","play in the park"]
];